services:
  server:
    build: ./server
    container_name: finance-bot-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: finance-bot-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
